### ISSUE TITLE
Add more lint reviews

### ISSUE THREAD

**Issue by sjparkinson** [sjparkinson/static-review#10]
- [ ] `.less` with [twitter/recess](https://github.com/twitter/recess)
- [ ] `.php` with [fabpot/PHP-CS-Fixer](https://github.com/fabpot/PHP-CS-Fixer)
- [ ] `.php` with [sebastianbergmann/phpcpd](https://github.com/sebastianbergmann/phpcpd)
- [ ] `.php` with [sebastianbergmann/phpdcd](https://github.com/sebastianbergmann/phpdcd)
- [ ] `.json` with [seld/jsonlint](https://github.com/seld/jsonlint)
- [ ] `*` trailing whitespace

**Done**
- [x] `.php` with [squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer)
- [x] `composer.lock` with [sensiolabs/security-checker](https://github.com/sensiolabs/security-checker)

**Comment by keradus** [comment]
any news on that?

**Comment by sjparkinson** [comment]
> any news on that?

Nope haven't been able to dedicate much time to projects lately. I'm more than happy to accept PR's for any of these!
