### ISSUE TITLE
phpunit fail at windows at develop branch

### ISSUE THREAD

**Issue by keradus** [sjparkinson/static-review#16]
phpunit fail at windows at develop branch:

```
PHPUnit 4.2.2 by Sebastian Bergmann.
...
There was 1 failure:

1) StaticReview\Test\Unit\Classes\FileTests::testGetMimeType
Failed asserting that false is true.

D:\GIT\fork\static-review\tests\unit\File\FileTest.php:125
C:\Users\keradus\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:186
C:\Users\keradus\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:138
[37;41m                                        [0m
[37;41mFAILURES!                               [0m
[37;41mTests: 81, Assertions: 142, Failures: 1.[0m
```

**Comment by keradus** [comment]
yeah, dead for 5 months

**Comment by keradus** [comment]
yey, dead for 8 months :D

**Comment by sjparkinson** [comment]
> yey, dead for 8 months :D

Apologies, it has been quite busy for me recently. I'm slowly working on the [5.0 branch][1], refactoring static-review into a single command symphony console application with a configuration file.

As marked, I'm aiming to resolve many of the issues in that release.

I'm happy to accept PR's in the meantime, but I'll be focusing on 5.0.

[1]: https://github.com/sjparkinson/static-review/tree/5.0
