### ISSUE TITLE
Add a Mercurial Adapter

### ISSUE THREAD

**Issue by sjparkinson** [sjparkinson/static-review#33]

**Comment by keradus** [comment]
Someone still uses it?
Maybe get some feedback of `static-review` users to be sure that this is really needed :D

**Comment by sjparkinson** [comment]
> Someone still uses it?

I've actually had no requests, but it's the only other major modern source control system, something I thought worth supporting.

I'll reopen this if a request does come in though, until then there's plenty of other things to focus on.

**Comment by keradus** [comment]
Great thought!
