### ISSUE TITLE
Incorrect EOL while getting changed files

### ISSUE THREAD

**Issue by Iskender-gen** [sjparkinson/static-review#38]
Hello, i'm trying to run pre-commit script and getting error
failed to open stream: Invalid argument in \vendor\sjparkinson\static-review\src\File\File.php on line 174.

After code exploration i found the string that works wrong on my environment.
\vendor\sjparkinson\static-review\src\VersionControl\GitVersionControl.php:78
`return array_filter(explode(PHP_EOL, $process->getOutput()));`

I'm using window 7 + git bash + portable LAMP server (OpenServer)
In my case explode returns array that contains only one string.
But if i change PHP_EOL by "\n" it works.

Looks like php uses the system EOL while git bash console uses the linux one

**Comment by sjparkinson** [comment]
Well that's interesting, the reason I used PHP_EOL was to help when running on different platforms.

I'll use `\n` instead and trim each line.

**Comment by Iskender-gen** [comment]
It can fix the problem. But also, there is another problem with the GIT under windows. With directory separators. The script can make file path and cmd like that: `vendor/bin/phpcs --report=json --standard=psr2 C:\OpenServer\userdata\temp/sjparkinson.static-review/cached/vendor/sjparkinson/static-review/src/VersionControl/GitVersionControl.php`

I think it's not a bug, but rather a feature of use GIT under Windows

**Comment by sjparkinson** [comment]
For my reference here's a good SO answer on the EOL issue: http://stackoverflow.com/a/4975441

I guess the path issue is similar because we're using `DIRECTORY_SEPARATOR`?

**Comment by Iskender-gen** [comment]
Yes, it  is. 
I'm still trying to run PhpCodeSnifferReview tool on my windows env, but there is no result.
I got new errors. If I can not fix them, i will try to run this on linux env.

**Comment by shadowhand** [comment]
I think we should use this to split lines:

```php
return array_filter(preg_split('/(?:\r\n|\r|\n)/', $process->getOutput()));
```

It will work with any combination of `CR`, `LF`, or `CRLF`.

**Comment by Serzhik** [comment]
Any updates?
