### ISSUE TITLE
Add phpunit/phpspec quality assurance review

### ISSUE THREAD

**Issue by bashilbers** [sjparkinson/static-review#51]
Seeing that StaticReview can only review staged files and the Commit Message, what about preventing the commit if the testsuite is not passing? - I am doing this in a shell script via pre-commit and would really like to port it to static-review

**Comment by shadowhand** [comment]
You certainly could write a review that would run a test suite. The only thing to be aware of would be execution time. And you might need to figure out how to stream the output of the suite during the test, which I'm not sure is currently supported.

**Comment by bashilbers** [comment]
Can u create a gitter channel please, I have some other questions/suggestions i'd like to propose and github issues does not feel right.. :grin:

**Comment by sjparkinson** [comment]
Of course, I'll get on that shortly.

**Comment by sjparkinson** [comment]
@bashilbers here you go: https://gitter.im/sjparkinson/static-review

I'm going to close this as it's probabily something to build seperatly, using this repo as a framework, I want to avoid this becoming a dump of various infrequently used reviews.
