### ISSUE TITLE
CodeSniffer review doesn't handle command line errors

### ISSUE THREAD

**Issue by liquorvicar** [sjparkinson/static-review#61]
If there is a problem with your CodeSniffer set up (e.g. binary is not at vendor/bin/phpcs, your standard is not installed etc), you get little or not feedback as to the problem.

In the latter case, I got this error:

```
Warning: array_reduce() expects parameter 1 to be array, null given in vendor/sjparkinson/static-review/src/Review/PHP/PhpCodeSnifferReview.php on line 114
PHP Warning:  Invalid argument supplied for foreach() in vendor/sjparkinson/static-review/src/Review/PHP/PhpCodeSnifferReview.php on line 114
```

**Comment by jyggen** [comment]
Seeing this as well. It's most likely the `json_decode()` in `PhpCodeSnifferReview.php` that fails since PHPCS returns an error (or even a PHP Warning/Notice) and thus the output isn't a valid JSON.
