### ISSUE TITLE
Consider a global configuration file

### ISSUE THREAD

**Issue by maschmann** [sjparkinson/static-review#63]
I've had a look into the implementation details of the reviews. They have a lot of hardcoded configuration options (parameters) or even binary paths.
How about making them default options and overwritable by a simple YAML config in the project root dir?
Something like "php-static-review.yml" :-)

What do you think?

**Comment by keradus** [comment]
Please no static-review, it's a different project: https://github.com/sjparkinson/static-review (and for same think, so no it would be extra ambiguous)

**Comment by keradus** [comment]
Wrong repo, please ignore me :D

**Comment by keradus** [comment]
sth like https://github.com/phpro/grumphp#configuration ?

BTW, guys, grumphp looks to do same thing. Maybe join forces ?

**Comment by maschmann** [comment]
There's another one: https://github.com/bruli/php-git-hooks

But I like it light-weighted like this one.

**Comment by sjparkinson** [comment]
I actually have a branch ([command-line-app](https://github.com/sjparkinson/static-review/tree/command-line-app)) that makes use of a configuration file, but I haven't found time to work on that in a while.

Totally makes sense though. Related to https://github.com/sjparkinson/static-review/issues/62.

**Comment by maschmann** [comment]
Maybe I can spare some time, the next few days - then I'll have a look into your branch :+1:
