### ISSUE TITLE
Suggestion: add searchable topics to project

### ISSUE THREAD

**Issue by mcampbell508** [sjparkinson/static-review#66]
Now that GitHub has introduced its [topic feature](https://help.github.com/articles/about-topics/) to make projects more searchable; I think it could really help others discover this great project, to add (at least) the following topics:

- `git-hooks`
- `version-control`
- `code-review`
- `code-style`
- `phpunit`

These are just suggestions for you to take on board if you'd like...

Anyways thanks!

**Comment by sjparkinson** [comment]
Done!
