### ISSUE TITLE
Is this Package Abandoned?

### ISSUE THREAD

**Issue by sjparkinson** [sjparkinson/static-review#69]
@keradus asks in #68:

> does this mean this package is abandoned?

Personally I'm not actively developing or using the project any more.

I was thinking about moving it to it's own org, `static-review/static-review`, and handing it over to the other contributors besides me, but that requires a rename. Not sure how much of a pain that would be.

Thoughts?

**Comment by keradus** [comment]
Raname on github is easy, rename in `composer.json` and packagist is hard, as you would ask all users to rename the required package in the end.

Package is great, it provided a lot of nice value and great ideas.
Don't get me wrong here, but maybe, just maybe, if you admit you, as creator, is not even using it anymore, maybe just deprecate package and redirect ppl to other one, eg https://github.com/phpro/grumphp ?

**Comment by sjparkinson** [comment]
> Don't get me wrong here, but maybe, just maybe, if you admit that you, as creator, is not even using it anymore, maybe just deprecate package and redirect ppl to other one, eg https://github.com/phpro/grumphp?

Not at all, I think that's an excellent suggestion.

I've been so long out of PHP I didn't even know that project existed. It's even got a logo 😀 !

I'll leave this up for a few days to ponder, see if anyone else has any thoughts, then will likely do just as you suggest.

**Comment by sjparkinson** [comment]
As discussed this is what I'm going to go with.

Will dig out my Packagist credentials, and update the readme.
