### ISSUE TITLE
Improve coverage of tested code

### ISSUE THREAD

**Issue by sjparkinson** [sjparkinson/static-review#7]
![Code Coverage](https://i.imgur.com/sq9fpoU.png)
## To Do
- [x] Functional tests for [`getStagedFiles()`](https://github.com/sjparkinson/static-review/blob/1.1.4/src/VersionControl/GitVersionControl.php#L24-L58) in `GitVersionControl`
- [ ] Functional tests for each [console command](https://github.com/sjparkinson/static-review/tree/4.1.1/src/Command)
- [ ] Functional tests for [`saveFileToCache()`](https://github.com/sjparkinson/static-review/blob/4.1.1/src/VersionControl/GitVersionControl.php#L84-L105) in `GitVersionControl`

**Comment by shadowhand** [comment]
Is the task description still up to date? Seems like the links are for very old versions?

**Comment by sjparkinson** [comment]
@shadowhand I haven't touched it in a while, so I'll update that coverage screenshot and the list. There's still room for more coverage.
